//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krkadoni.EnigmaSettings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krkadoni.EnigmaSettings.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot change flag value before specifing flag. ähnelt.
        /// </summary>
        public static string Flag_FlagValue_Cannot_change_flag_value_before_specifing_flag_ {
            get {
                return ResourceManager.GetString("Flag_FlagValue_Cannot_change_flag_value_before_specifing_flag_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flag string cannot be empty. ähnelt.
        /// </summary>
        public static string Flag_New_Flag_string_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("Flag_New_Flag_string_cannot_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid flag ähnelt.
        /// </summary>
        public static string Flag_New_Invalid_flag {
            get {
                return ResourceManager.GetString("Flag_New_Invalid_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service name cannot be empty ähnelt.
        /// </summary>
        public static string Service_New_Service_name_cannot_be_empty {
            get {
                return ResourceManager.GetString("Service_New_Service_name_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid service data. ähnelt.
        /// </summary>
        public static string Service_ServiceData_Invalid_service_data_ {
            get {
                return ResourceManager.GetString("Service_ServiceData_Invalid_service_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service data cannot be empty. ähnelt.
        /// </summary>
        public static string Service_ServiceData_Service_data_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("Service_ServiceData_Service_data_cannot_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added new transponder {0} for previously missing cable ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLCables_Added_new_transponder__0__for_previously_missing_cable {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLCables_Added_new_transponder__0__for_previously_missing_cab" +
                        "le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to update missing XML cables ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLCables_Failed_to_update_missing_XML_cables {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLCables_Failed_to_update_missing_XML_cables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New cable added to cables ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLCables_New_cable__added_to_cables {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLCables_New_cable__added_to_cables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added new transponder {0} for previously missing satellite {1} ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLSatellites_Added_new_transponder__0__for_previously_missing_satellite__1_ {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLSatellites_Added_new_transponder__0__for_previously_missing" +
                        "_satellite__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to update missing XML satellites ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLSatellites_Failed_to_update_missing_XML_satellites {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLSatellites_Failed_to_update_missing_XML_satellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New satellite for position {0} added to satellites ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLSatellites_New_satellite_for_position__0__added_to_satellites {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLSatellites_New_satellite_for_position__0__added_to_satellit" +
                        "es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING: Some transponders are market as satellite but have invalid position 0 degrees! ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLSatellites_WARNING__Some_transponders_are_market_as_satellite_but_have_invalid_position_0_degrees_ {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLSatellites_WARNING__Some_transponders_are_market_as_satelli" +
                        "te_but_have_invalid_position_0_degrees_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to update missing XML transponders ähnelt.
        /// </summary>
        public static string Settings_AddMissingXMLTransponders_Failed_to_update_missing_XML_transponders {
            get {
                return ResourceManager.GetString("Settings_AddMissingXMLTransponders_Failed_to_update_missing_XML_transponders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot change position for satellite {1} to {2}.{0}There is already satellite on this position ähnelt.
        /// </summary>
        public static string Settings_ChangeSatellitePosition_Cannot_change_position_for_satellite__1__to__2___0_There_is_already_satellite_on_this_position {
            get {
                return ResourceManager.GetString("Settings_ChangeSatellitePosition_Cannot_change_position_for_satellite__1__to__2__" +
                        "_0_There_is_already_satellite_on_this_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load settings from {0} ähnelt.
        /// </summary>
        public static string Settings_Load_Failed_to_load_settings_from__0_ {
            get {
                return ResourceManager.GetString("Settings_Load_Failed_to_load_settings_from__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading settings from {0} ähnelt.
        /// </summary>
        public static string Settings_Load_Loading_settings_from__0_ {
            get {
                return ResourceManager.GetString("Settings_Load_Loading_settings_from__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} does not exist ähnelt.
        /// </summary>
        public static string Settings_LoadSettings_File__0__does_not_exist_ {
            get {
                return ResourceManager.GetString("Settings_LoadSettings_File__0__does_not_exist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid filename! ähnelt.
        /// </summary>
        public static string Settings_LoadSettings_Invalid_filename_ {
            get {
                return ResourceManager.GetString("Settings_LoadSettings_Invalid_filename_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bouquet service {0} not found in settings ähnelt.
        /// </summary>
        public static string Settings_MatchBouquetServices_Bouquet_service__0__not_found_in_settings {
            get {
                return ResourceManager.GetString("Settings_MatchBouquetServices_Bouquet_service__0__not_found_in_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while matching bouquet items to services ähnelt.
        /// </summary>
        public static string Settings_MatchBouquetServices_There_was_an_error_while_matching_bouquet_items_to_services {
            get {
                return ResourceManager.GetString("Settings_MatchBouquetServices_There_was_an_error_while_matching_bouquet_items_to_" +
                        "services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No satellite has been found for transponder {0} ähnelt.
        /// </summary>
        public static string Settings_MatchSatellitesWithTransponders_No_satellite_has_been_found_for_transponder__0_ {
            get {
                return ResourceManager.GetString("Settings_MatchSatellitesWithTransponders_No_satellite_has_been_found_for_transpon" +
                        "der__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while matching transponders with satellites. ähnelt.
        /// </summary>
        public static string Settings_MatchSatellitesWithTransponders_There_was_an_error_while_matching_transponders_with_satellites_ {
            get {
                return ResourceManager.GetString("Settings_MatchSatellitesWithTransponders_There_was_an_error_while_matching_transp" +
                        "onders_with_satellites_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No transponder has been found for service {0}   {1} ähnelt.
        /// </summary>
        public static string Settings_MatchServicesWithTransponders_No_transponder_has_been_found_for_service__0_____1_ {
            get {
                return ResourceManager.GetString("Settings_MatchServicesWithTransponders_No_transponder_has_been_found_for_service_" +
                        "_0_____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while trying to match services with transponders ähnelt.
        /// </summary>
        public static string Settings_MatchServicesWithTransponders_There_was_an_error_while_trying_to_match_services_with_transponders {
            get {
                return ResourceManager.GetString("Settings_MatchServicesWithTransponders_There_was_an_error_while_trying_to_match_s" +
                        "ervices_with_transponders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while moving satellite to a new position ähnelt.
        /// </summary>
        public static string Settings_MoveSatellite_There_was_an_error_while_moving_satellite_to_a_new_position {
            get {
                return ResourceManager.GetString("Settings_MoveSatellite_There_was_an_error_while_moving_satellite_to_a_new_positio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to read file {0}{1}{2} ähnelt.
        /// </summary>
        public static string Settings_Read_Failed_to_read_file__0__1__2_ {
            get {
                return ResourceManager.GetString("Settings_Read_Failed_to_read_file__0__1__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} read in {1} ms ähnelt.
        /// </summary>
        public static string Settings_Read_File__0__read_in__1__ms {
            get {
                return ResourceManager.GetString("Settings_Read_File__0__read_in__1__ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename cannot be empty ähnelt.
        /// </summary>
        public static string Settings_Read_Filename_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("Settings_Read_Filename_cannot_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading file {0} ähnelt.
        /// </summary>
        public static string Settings_Read_Reading_file__0_ {
            get {
                return ResourceManager.GetString("Settings_Read_Reading_file__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bouquet {0} in bouquet {1} is of unknown type ähnelt.
        /// </summary>
        public static string Settings_ReadBouquet_Bouquet__0__in_bouquet__1__is_of_unknown_type {
            get {
                return ResourceManager.GetString("Settings_ReadBouquet_Bouquet__0__in_bouquet__1__is_of_unknown_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bouquet {0} is empty ähnelt.
        /// </summary>
        public static string Settings_ReadBouquet_Bouquet__0__is_empty {
            get {
                return ResourceManager.GetString("Settings_ReadBouquet_Bouquet__0__is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to read bouquet {0} ähnelt.
        /// </summary>
        public static string Settings_ReadBouquet_Failed_to_read_bouquet__0_ {
            get {
                return ResourceManager.GetString("Settings_ReadBouquet_Failed_to_read_bouquet__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No &apos;{0}&apos; tag was found in file {1} ähnelt.
        /// </summary>
        public static string Settings_ReadBouquet_No___0___tag_was_found_in_file__1_ {
            get {
                return ResourceManager.GetString("Settings_ReadBouquet_No___0___tag_was_found_in_file__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream service {1} added to bouquet {0} without description ähnelt.
        /// </summary>
        public static string Settings_ReadBouquet_Stream_service__1__added_to_bouquet__0__without_description {
            get {
                return ResourceManager.GetString("Settings_ReadBouquet_Stream_service__1__added_to_bouquet__0__without_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported line &apos;{1}&apos; in bouquet {0} ähnelt.
        /// </summary>
        public static string Settings_ReadBouquet_Unsupported_line___1___in_bouquet__0_ {
            get {
                return ResourceManager.GetString("Settings_ReadBouquet_Unsupported_line___1___in_bouquet__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} is unknown bouquet type ähnelt.
        /// </summary>
        public static string Settings_ReadBouquets_File__0__is_unknown_bouquet_type {
            get {
                return ResourceManager.GetString("Settings_ReadBouquets_File__0__is_unknown_bouquet_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignoring line {0} in Enigma1 bouquet {1}, doesn&apos;t look like regular service ähnelt.
        /// </summary>
        public static string Settings_ReadE1Bouquets_Ignoring_line__0__in_Enigma1_bouquet__1___doesn_t_look_like_regular_service {
            get {
                return ResourceManager.GetString("Settings_ReadE1Bouquets_Ignoring_line__0__in_Enigma1_bouquet__1___doesn_t_look_li" +
                        "ke_regular_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} is empty ähnelt.
        /// </summary>
        public static string Settings_ReadServicesFile_File__0__is_empty_ {
            get {
                return ResourceManager.GetString("Settings_ReadServicesFile_File__0__is_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} is not valid settings file ähnelt.
        /// </summary>
        public static string Settings_ReadServicesFile_File__0__is_not_valid_settings_file_ {
            get {
                return ResourceManager.GetString("Settings_ReadServicesFile_File__0__is_not_valid_settings_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No &apos;services&apos; tag was found in file {0} ähnelt.
        /// </summary>
        public static string Settings_ReadServicesFile_No__services__tag_was_found_in_file__0_ {
            get {
                return ResourceManager.GetString("Settings_ReadServicesFile_No__services__tag_was_found_in_file__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No &apos;transponder&apos; tag was found in {0} ähnelt.
        /// </summary>
        public static string Settings_ReadServicesFile_No__transponder__tag_was_found_in__0_ {
            get {
                return ResourceManager.GetString("Settings_ReadServicesFile_No__transponder__tag_was_found_in__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while reading settings{0}{1} ähnelt.
        /// </summary>
        public static string Settings_ReadServicesFile_There_was_an_error_while_reading_services_0__1_ {
            get {
                return ResourceManager.GetString("Settings_ReadServicesFile_There_was_an_error_while_reading_services_0__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported settings version {0} ähnelt.
        /// </summary>
        public static string Settings_ReadServicesFile_Unsuported_settings_version__0_ {
            get {
                return ResourceManager.GetString("Settings_ReadServicesFile_Unsuported_settings_version__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing cable ähnelt.
        /// </summary>
        public static string Settings_RemoveCable_There_was_an_error_while_removing_cable {
            get {
                return ResourceManager.GetString("Settings_RemoveCable_There_was_an_error_while_removing_cable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing double markers ähnelt.
        /// </summary>
        public static string Settings_RemoveDoubleMarkers_There_was_an_error_while_removing_double_markers {
            get {
                return ResourceManager.GetString("Settings_RemoveDoubleMarkers_There_was_an_error_while_removing_double_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing empty bouquets ähnelt.
        /// </summary>
        public static string Settings_RemoveEmptyBouquets_There_was_an_error_while_removing_empty_bouquets {
            get {
                return ResourceManager.GetString("Settings_RemoveEmptyBouquets_There_was_an_error_while_removing_empty_bouquets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing invalid bouquet items ähnelt.
        /// </summary>
        public static string Settings_RemoveInvalidBouquetItems_There_was_an_error_while_removing_invalid_bouquet_items {
            get {
                return ResourceManager.GetString("Settings_RemoveInvalidBouquetItems_There_was_an_error_while_removing_invalid_bouq" +
                        "uet_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing satellite ähnelt.
        /// </summary>
        public static string Settings_RemoveSatellite_There_was_an_error_while_removing_satellite {
            get {
                return ResourceManager.GetString("Settings_RemoveSatellite_There_was_an_error_while_removing_satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing service {0} ähnelt.
        /// </summary>
        public static string Settings_RemoveService_There_was_an_error_while_removing_service__0_ {
            get {
                return ResourceManager.GetString("Settings_RemoveService_There_was_an_error_while_removing_service__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while deleting services ähnelt.
        /// </summary>
        public static string Settings_RemoveServices_There_was_an_error_while_deleting_services {
            get {
                return ResourceManager.GetString("Settings_RemoveServices_There_was_an_error_while_deleting_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing streams ähnelt.
        /// </summary>
        public static string Settings_RemoveStreams_There_was_an_error_while_removing_streams {
            get {
                return ResourceManager.GetString("Settings_RemoveStreams_There_was_an_error_while_removing_streams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing transponder {0} ähnelt.
        /// </summary>
        public static string Settings_RemoveTransponder_There_was_an_error_while_removing_transponder__0_ {
            get {
                return ResourceManager.GetString("Settings_RemoveTransponder_There_was_an_error_while_removing_transponder__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while removing transponders ähnelt.
        /// </summary>
        public static string Settings_RemoveTransponders_There_was_an_error_while_removing_transponders {
            get {
                return ResourceManager.GetString("Settings_RemoveTransponders_There_was_an_error_while_removing_transponders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while trying to renumber bouquet file names. ähnelt.
        /// </summary>
        public static string Settings_RenumberBouquetFileNames_There_was_an_error_while_trying_to_renumber_bouquet_file_names_ {
            get {
                return ResourceManager.GetString("Settings_RenumberBouquetFileNames_There_was_an_error_while_trying_to_renumber_bou" +
                        "quet_file_names_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while renumbering markers. ähnelt.
        /// </summary>
        public static string Settings_RenumberMarkers_There_was_an_error_while_renumbering_markers_ {
            get {
                return ResourceManager.GetString("Settings_RenumberMarkers_There_was_an_error_while_renumbering_markers_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while updating namespaces for satellite transponders. ähnelt.
        /// </summary>
        public static string Settings_UpdateSatelliteTranspondersNameSpaces_There_was_an_error_while_updating_namespaces_for_satellite_transponders_ {
            get {
                return ResourceManager.GetString("Settings_UpdateSatelliteTranspondersNameSpaces_There_was_an_error_while_updating_" +
                        "namespaces_for_satellite_transponders_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} already exists and could not be deleted! ähnelt.
        /// </summary>
        public static string SettingsIO_DeleteFileIfExists_File__0__already_exists_and_could_not_be_deleted_ {
            get {
                return ResourceManager.GetString("SettingsIO_DeleteFileIfExists_File__0__already_exists_and_could_not_be_deleted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service {0} in bouquet {1} has no matching transponder. Not writing it. ähnelt.
        /// </summary>
        public static string SettingsIO_E1BouquetToString_Service__0__in_bouquet__1__has_no_matching_transponder__Not_writing_it_ {
            get {
                return ResourceManager.GetString("SettingsIO_E1BouquetToString_Service__0__in_bouquet__1__has_no_matching_transpond" +
                        "er__Not_writing_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service {0} in bouquet {1} is not supported in Enigma1. Not writing it. ähnelt.
        /// </summary>
        public static string SettingsIO_E1BouquetToString_Service__0__in_bouquet__1__is_not_supported_in_Enigma1__Not_writing_it_ {
            get {
                return ResourceManager.GetString("SettingsIO_E1BouquetToString_Service__0__in_bouquet__1__is_not_supported_in_Enigm" +
                        "a1__Not_writing_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service reference {0} in bouquet {1} is not matched to any service. Not writing it to bouquet. ähnelt.
        /// </summary>
        public static string SettingsIO_E1BouquetToString_Service_reference__0__in_bouquet__1__is_not_matched_to_any_service__Not_writing_it_to_bouquet_ {
            get {
                return ResourceManager.GetString("SettingsIO_E1BouquetToString_Service_reference__0__in_bouquet__1__is_not_matched_" +
                        "to_any_service__Not_writing_it_to_bouquet_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid instance factory! ähnelt.
        /// </summary>
        public static string SettingsIO_New_Invalid_instance_factory_ {
            get {
                return ResourceManager.GetString("SettingsIO_New_Invalid_instance_factory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to read Enigma1 bouquets file. ähnelt.
        /// </summary>
        public static string SettingsIO_ReadE1Bouquets_Failed_to_read_Enigma1_bouquets_file_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadE1Bouquets_Failed_to_read_Enigma1_bouquets_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid service reference {0} not added to bouquet {1} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadFileBouquet_Invalid_service_reference__0__not_added_to_bouquet__1_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadFileBouquet_Invalid_service_reference__0__not_added_to_bouquet__1_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid stream reference {0} not added to bouquet {1} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadFileBouquet_Invalid_stream_reference__0__not_added_to_bouquet__1_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadFileBouquet_Invalid_stream_reference__0__not_added_to_bouquet__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to initialize new marker from line {0} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadMarkerReference_Failed_to_initialize_new_marker_from_line__0_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadMarkerReference_Failed_to_initialize_new_marker_from_line__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to initialize new service from line {0} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServiceReference_Failed_to_initialize_new_service_from_line__0_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServiceReference_Failed_to_initialize_new_service_from_line__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locked bouquet number {0} has no matching Enigma1 bouquet. ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServicesLocked_Bouquet_item__0__has_no_matching_Enigma1_bouquet_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServicesLocked_Bouquet_item__0__has_no_matching_Enigma1_bouquet_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to read services.locked file ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServicesLocked_Failed_to_read_services_locked_file {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServicesLocked_Failed_to_read_services_locked_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found unknown reference type {0} in {1} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServicesLocked_Found_unknown_reference_type__0__in__1_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServicesLocked_Found_unknown_reference_type__0__in__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid line {0} found in {1} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServicesLocked_Invalid_line__0__found_in__1_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServicesLocked_Invalid_line__0__found_in__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locked bouquet item {0} has no matching service ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServicesLocked_Locked_bouquet_item__0__has_no_matching_service {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServicesLocked_Locked_bouquet_item__0__has_no_matching_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to parse bouquet order number {0} to integer for bouquet {1} on line {2} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServicesLocked_Unable_to_parse_bouquet_order_number__0__to_integer_for_bouquet__1__on_line__2_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServicesLocked_Unable_to_parse_bouquet_order_number__0__to_integer" +
                        "_for_bouquet__1__on_line__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported type {0} found in line {1} in file {2} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadServicesLocked_Unsupported_type__0__found_in_line__1__in_file__2_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadServicesLocked_Unsupported_type__0__found_in_line__1__in_file__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown transponder type for transponder {0} {1} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadSettingsFile_Unknown_transponder_type_for_transponder__0___1_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadSettingsFile_Unknown_transponder_type_for_transponder__0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to initialize new stream reference from line {0} ähnelt.
        /// </summary>
        public static string SettingsIO_ReadStreamReference_Failed_to_initialize_new_stream_reference_from_line__0_ {
            get {
                return ResourceManager.GetString("SettingsIO_ReadStreamReference_Failed_to_initialize_new_stream_reference_from_lin" +
                        "e__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bouquet filenames are not unique. ähnelt.
        /// </summary>
        public static string SettingsIO_Save_Bouquet_filenames_are_not_unique_ {
            get {
                return ResourceManager.GetString("SettingsIO_Save_Bouquet_filenames_are_not_unique_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to save settings to {0} ähnelt.
        /// </summary>
        public static string SettingsIO_Save_Failed_to_save_settings_to__0_ {
            get {
                return ResourceManager.GetString("SettingsIO_Save_Failed_to_save_settings_to__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error creating folder {0} ähnelt.
        /// </summary>
        public static string SettingsIO_Save_There_was_an_error_creating_folder__0_ {
            get {
                return ResourceManager.GetString("SettingsIO_Save_There_was_an_error_creating_folder__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service {0} has no transponder set, not writing it to settings. ähnelt.
        /// </summary>
        public static string SettingsIO_ServicesToString_Service__0__has_no_transponder_set__not_writing_it_to_settings_ {
            get {
                return ResourceManager.GetString("SettingsIO_ServicesToString_Service__0__has_no_transponder_set__not_writing_it_to" +
                        "_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service {0} has no matching transponder, not adding it to blacklist file ähnelt.
        /// </summary>
        public static string SettingsIO_WriteBlackList_Service__0__has_no_matching_transponder__not_adding_it_to_blacklist_file {
            get {
                return ResourceManager.GetString("SettingsIO_WriteBlackList_Service__0__has_no_matching_transponder__not_adding_it_" +
                        "to_blacklist_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skipping unknown bouquet item type in bouquet {0} ähnelt.
        /// </summary>
        public static string SettingsIO_WriteBouquets_Skipping_unknown_bouquet_item_type_in_bouquet__0_ {
            get {
                return ResourceManager.GetString("SettingsIO_WriteBouquets_Skipping_unknown_bouquet_item_type_in_bouquet__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference to Enigma1 bouquet {0} has no matching bouquet set, not adding it to bouquets file ähnelt.
        /// </summary>
        public static string SettingsIO_WriteEnigma1Bouquets_Reference_to_Enigma1_bouquet__0__has_no_matching_bouquet_set__not_adding_it_to_bouquets_file {
            get {
                return ResourceManager.GetString("SettingsIO_WriteEnigma1Bouquets_Reference_to_Enigma1_bouquet__0__has_no_matching_" +
                        "bouquet_set__not_adding_it_to_bouquets_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service {0} in Enigma1 bouqet {0} has no matching transponder, not adding it to bouquets file. ähnelt.
        /// </summary>
        public static string SettingsIO_WriteEnigma1Bouquets_Service__0__in_Enigma1_bouqet__0__has_no_matching_transponder__not_adding_it_to_bouquets_file_ {
            get {
                return ResourceManager.GetString("SettingsIO_WriteEnigma1Bouquets_Service__0__in_Enigma1_bouqet__0__has_no_matching" +
                        "_transponder__not_adding_it_to_bouquets_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service reference {0} has no matching service, not adding it to bouquet {1} ähnelt.
        /// </summary>
        public static string SettingsIO_WriteEnigma1Bouquets_Service_reference__0__has_no_matching_service__not_adding_it_to_bouquet__1_ {
            get {
                return ResourceManager.GetString("SettingsIO_WriteEnigma1Bouquets_Service_reference__0__has_no_matching_service__no" +
                        "t_adding_it_to_bouquet__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to write services.locked file to {0} ähnelt.
        /// </summary>
        public static string SettingsIO_WriteServicesLocked_Failed_to_write_services_locked_file_to__0_ {
            get {
                return ResourceManager.GetString("SettingsIO_WriteServicesLocked_Failed_to_write_services_locked_file_to__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference to Enigma1 bouquet {0} has no matching bouquet set, not adding it to services.locked ähnelt.
        /// </summary>
        public static string SettingsIO_WriteServicesLocked_Reference_to_Enigma1_bouquet__0__has_no_matching_bouquet_set__not_adding_it_to_services_locked {
            get {
                return ResourceManager.GetString("SettingsIO_WriteServicesLocked_Reference_to_Enigma1_bouquet__0__has_no_matching_b" +
                        "ouquet_set__not_adding_it_to_services_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service {0} has no transponder, not adding it to services.locked ähnelt.
        /// </summary>
        public static string SettingsIO_WriteServicesLocked_Service__0__has_no_transponder__not_adding_it_to_services_locked {
            get {
                return ResourceManager.GetString("SettingsIO_WriteServicesLocked_Service__0__has_no_transponder__not_adding_it_to_s" +
                        "ervices_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to write bouquet {0} to {1} ähnelt.
        /// </summary>
        public static string SettingsIO_WriteTvBouquetsE2_Failed_to_write_bouquet__0__to__1_ {
            get {
                return ResourceManager.GetString("SettingsIO_WriteTvBouquetsE2_Failed_to_write_bouquet__0__to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service {0} has no matching transponder, not adding it to whitelist file ähnelt.
        /// </summary>
        public static string SettingsIO_WriteWhiteList_Service__0__has_no_matching_transponder__not_adding_it_to_whitelist_file {
            get {
                return ResourceManager.GetString("SettingsIO_WriteWhiteList_Service__0__has_no_matching_transponder__not_adding_it_" +
                        "to_whitelist_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid transponder type! ähnelt.
        /// </summary>
        public static string Transponder_New_Invalid_transponder_type_ {
            get {
                return ResourceManager.GetString("Transponder_New_Invalid_transponder_type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid file provider ähnelt.
        /// </summary>
        public static string XmlSatellitesIO_XmlSatellitesIO_Invalid_file_provider {
            get {
                return ResourceManager.GetString("XmlSatellitesIO_XmlSatellitesIO_Invalid_file_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid path provider ähnelt.
        /// </summary>
        public static string XmlSatellitesIO_XmlSatellitesIO_Invalid_path_provider {
            get {
                return ResourceManager.GetString("XmlSatellitesIO_XmlSatellitesIO_Invalid_path_provider", resourceCulture);
            }
        }
    }
}
